server:
  servlet:
    encoding:
      charset: UTF-8
    context-path: /api-recicla

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            handler:
              HandlerMappingIntrospector: ERROR

topicos:
  executar-pagamento: "executar-pagamento"
  transacao-confirmada: "transacao-confirmada"

spring:
  servlet:
    multipart:
      enabled:true
      max-file-size=5MB
      max-request-size=5MB
  profiles:
    default: heroku
    active: heroku