server:
  servlet:
    encoding:
      charset: UTF-8
    context-path: /api-recicla
spring:
  profiles:
    default: heroku
    active: heroku
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            handler:
              HandlerMappingIntrospector: ERROR